config/routes.rb
Rails.application.routes.draw do

  root to: 'buses#show', id:'1'

  resources :buses

end

app/models/bathroom.rb
class Bathroom < BusElement

end

app/models/bus.rb
class Bus < ActiveRecord::Base
	has_many :bus_elements

	def elements_max field
		bus_elements.pluck(field).max
	end

	def elements_min field
		bus_elements.pluck(field).min
	end

	def get_element_type row, column
		element = bus_elements.select do |element|
			element.row == row and
			element.column == column
		end.first
		if element
			element.type
		end
	end

	def seat_number row, column
		column_plus = column < 3 ? column : column - 1
		seats_number = (row - 2)*4 + column_plus
	end

end

app/models/bus_element.rb
class BusElement < ActiveRecord::Base
  belongs_to :bus
end

app/models/door.rb
class Door < BusElement

end

app/models/driver_seat.rb
class DriverSeat < BusElement

end

app/models/seat.rb
class Seat < BusElement

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/buses_controller.rb
class BusesController < ApplicationController
  before_action :set_bus, only: [:show, :edit, :update, :destroy]

  # GET /buses
  # GET /buses.json
  def index
    @buses = Bus.all
  end

  # GET /buses/1
  # GET /buses/1.json
  def show
  end

  # GET /buses/new
  def new
    @bus = Bus.new
  end

  # GET /buses/1/edit
  def edit
  end

  # POST /buses
  # POST /buses.json
  def create
    @bus = Bus.new(bus_params)

    respond_to do |format|
      if @bus.save
        format.html { redirect_to @bus, notice: 'Bus was successfully created.' }
        format.json { render :show, status: :created, location: @bus }
      else
        format.html { render :new }
        format.json { render json: @bus.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /buses/1
  # PATCH/PUT /buses/1.json
  def update
    respond_to do |format|
      if @bus.update(bus_params)
        format.html { redirect_to @bus, notice: 'Bus was successfully updated.' }
        format.json { render :show, status: :ok, location: @bus }
      else
        format.html { render :edit }
        format.json { render json: @bus.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /buses/1
  # DELETE /buses/1.json
  def destroy
    @bus.destroy
    respond_to do |format|
      format.html { redirect_to buses_url, notice: 'Bus was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_bus
      @bus = Bus.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def bus_params
      params[:bus]
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/buses_helper.rb
module BusesHelper
end

app/views/buses/_form.html.erb
<%= form_for(@bus) do |f| %>
  <% if @bus.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@bus.errors.count, "error") %> prohibited this bus from being saved:</h2>

      <ul>
      <% @bus.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/buses/edit.html.erb
<h1>Editing Bus</h1>

<%= render 'form' %>

<%= link_to 'Show', @bus %> |
<%= link_to 'Back', buses_path %>

app/views/buses/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Buses</h1>

<table>
  <thead>
    <tr>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @buses.each do |bus| %>
      <tr>
        <td><%= link_to 'Show', bus %></td>
        <td><%= link_to 'Edit', edit_bus_path(bus) %></td>
        <td><%= link_to 'Destroy', bus, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Bus', new_bus_path %>

app/views/buses/new.html.erb
<h1>New Bus</h1>

<%= render 'form' %>

<%= link_to 'Back', buses_path %>

app/views/buses/show.html.haml
%table.info
	%tr
		%th= "Bus"
		%td= @bus.patent
	%tr
		%th= "Marca"
		%td= @bus.mark
	%tr
		%th= "Modelo"
		%td= @bus.model
	%tr
		%th= "Año"
		%td= @bus.year

%h1= "Layout"

%table.layout
	- # Iteramos sobre las "columnas" del bus, desde la mayor (lado derecho) a la menor (lado izquierdo), pues el lado derecho del bus queda "arriba" al mostrarlo acostado
	- (@bus.elements_min(:column)..@bus.elements_max(:column)).reverse_each do |column|
		%tr
			- # Ahora iteramos sobre las "filas" del bus
			- (@bus.elements_min(:row)..@bus.elements_max(:row)).each do |row|
				%td
					- case @bus.get_element_type row, column
					- when 'Seat' # Asiento
						- #aumentamos contador
						%input{ :type => "checkbox", :row => row, :column => column }
							= @bus.seat_number(row, column)
					- when 'DriverSeat' # indica la ubicación del chofer en el bus
						Dr
					- when 'Door' # indica una puerta
						Do 
					- when 'Bathroom' # indica baño
						WC
					- else # vacío
						- ' '

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>TestProject</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>